/*
 * FindBackPWFrm_sub.java
 *
 * Created on __DATE__, __TIME__
 */

package com.Zs.View;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.Vector;

import javax.swing.JOptionPane;

import ZsUtil.ZsUtil;

import com.Zs.DbDao.DbLogUserDao;
import com.Zs.DbUtil.DbUtil;

/**
 *
 * @author  __USER__
 */
public class FindBackPWFrm_sub extends javax.swing.JFrame {
	DbLogUserDao daDbLogUserDao = new DbLogUserDao();
	DbUtil dbUtil = new DbUtil();
	Vector<String> v = null;

	/** Creates new form FindBackPWFrm_sub */
	public FindBackPWFrm_sub() {
		initComponents();
		//设置fram居中显示
		this.setLocationRelativeTo(null);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		UserTxt = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		Q_Label1 = new javax.swing.JLabel();
		Q_Label2 = new javax.swing.JLabel();
		Q_Label3 = new javax.swing.JLabel();
		A1_Txt = new javax.swing.JTextField();
		A2_Txt = new javax.swing.JTextField();
		A3_Txt = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);
		setUndecorated(true);

		UserTxt.addAncestorListener(new javax.swing.event.AncestorListener() {
			public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
			}

			public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
				UserTxtAncestorAdded(evt);
			}

			public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
			}
		});

		jButton1.setText("\u786e\u5b9a");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton1ActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		Q_Label1.setText("\u95ee\u9898\u4e00");

		Q_Label2.setText("\u95ee\u9898\u4e8c");

		Q_Label3.setText("\u95ee\u9898\u4e09");

		A1_Txt.setText("\u95ee\u9898\u4e00\u7b54\u6848");

		A2_Txt.setText("\u95ee\u9898\u4e8c\u7b54\u6848");

		A3_Txt.setText("\u95ee\u9898\u4e09\u7b54\u6848");

		jLabel4.setText("\u8bf7\u8f93\u5165\u7528\u6237\u540d");

		jButton2.setText("\u63d0\u4ea4");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setText("\u8fd4\u56de");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGap(41, 41, 41)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														A1_Txt,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														246, Short.MAX_VALUE)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		jLabel4)
																.addGap(18, 18,
																		18)
																.addComponent(
																		UserTxt,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		156,
																		Short.MAX_VALUE))
												.addComponent(Q_Label2)
												.addComponent(Q_Label3)
												.addComponent(Q_Label1)
												.addComponent(
														A2_Txt,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														246, Short.MAX_VALUE)
												.addComponent(
														A3_Txt,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														246, Short.MAX_VALUE))
								.addGap(42, 42, 42)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING,
												false)
												.addComponent(
														jButton3,
														javax.swing.GroupLayout.Alignment.LEADING,
														0, 0, Short.MAX_VALUE)
												.addComponent(
														jButton2,
														javax.swing.GroupLayout.Alignment.LEADING,
														0, 0, Short.MAX_VALUE)
												.addComponent(
														jButton1,
														javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														64, Short.MAX_VALUE))
								.addGap(29, 29, 29)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(39, 39, 39)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton1)
												.addComponent(jLabel4)
												.addComponent(
														UserTxt,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(30, 30, 30)
								.addComponent(Q_Label1)
								.addGap(14, 14, 14)
								.addComponent(A1_Txt,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(Q_Label2)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(A2_Txt,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(13, 13, 13)
								.addComponent(Q_Label3)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														A3_Txt,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jButton2))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										23, Short.MAX_VALUE)
								.addComponent(jButton3).addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		if( ZsUtil.stringIsEmpty(this.UserTxt.getText()) )
		{
			JOptionPane.showMessageDialog(null, "请输入用户名");
			return;
		}
		if(AnswerIsTure())
		{
			JOptionPane.showMessageDialog(null, "请设置您的新密码");
			this.dispose();
			FindBackPWFrm  a = new FindBackPWFrm();
			a.setVisible(true);
			a.setID(v.get(7));//将ID传到新窗口
			return;
		}

		JOptionPane.showMessageDialog(null, "你的回答有误");
	}

	private boolean AnswerIsTure() {
		if (v == null) {
			JOptionPane.showMessageDialog(null, "请输入正确的用户名");
			return false;
		}
		System.out.println( A1_Txt.getText()+v.get(3)+
				A2_Txt.getText()+v.get(4)+
				A3_Txt.getText()+v.get(5)
			);
		if ( (A1_Txt.getText().equals(v.get(3))) && 
			 (A2_Txt.getText().equals(v.get(4))) && 
			 (A3_Txt.getText().equals(v.get(5)))
			)
		{
			return true;
		}

		return false;
	}

	private void UserTxtAncestorAdded(javax.swing.event.AncestorEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
			throws Exception {
		Connection con = dbUtil.getCon();

		v = daDbLogUserDao.getSearchingDbQusetionPassword(con, "User",
				this.UserTxt.getText());
		if (v == null) {
			this.Q_Label1.setText("问题一");
			this.Q_Label2.setText("问题二");
			this.Q_Label3.setText("问题三");
		}
		if (ZsUtil.stringIsEmpty(this.UserTxt.getText())) {
			JOptionPane.showMessageDialog(null, "用户请输入用户名");
			return;
		}
		if (v == null) {
			JOptionPane.showMessageDialog(null, "无此用户");
			return;
		}

		this.Q_Label1.setText(v.get(0));
		this.Q_Label2.setText(v.get(1));
		this.Q_Label3.setText(v.get(2));

	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
		new LogFrm().setVisible(true);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new FindBackPWFrm_sub().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextField A1_Txt;
	private javax.swing.JTextField A2_Txt;
	private javax.swing.JTextField A3_Txt;
	private javax.swing.JLabel Q_Label1;
	private javax.swing.JLabel Q_Label2;
	private javax.swing.JLabel Q_Label3;
	private javax.swing.JTextField UserTxt;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel4;
	// End of variables declaration//GEN-END:variables

}