/*
 * FindBackPWFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.Zs.View;

import java.sql.Connection;

import javax.swing.JOptionPane;

import com.Zs.DbDao.DbLogUserDao;
import com.Zs.DbUtil.DbUtil;

/**
 *
 * @author  __USER__
 */
public class FindBackPWFrm extends javax.swing.JFrame {
	private String ID = "";
	private DbLogUserDao dbLogUserDao = new DbLogUserDao();
	private DbUtil dbUtil = new DbUtil();

	public String getID() {
		return ID;
	}

	public void setID(String iD) {
		ID = iD;
	}

	/** Creates new form FindBackPWFrm */
	public FindBackPWFrm() {
		initComponents();
		//设置fram居中显示
		this.setLocationRelativeTo(null);
		//this.setUndecorated(true); 
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		Password_New = new javax.swing.JPasswordField();
		Password_Confirm = new javax.swing.JPasswordField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);
		setUndecorated(true);

		jLabel1.setText("\u65b0 \u5bc6 \u7801");

		jLabel2.setText("\u786e\u8ba4\u5bc6\u7801");

		jButton1.setText("\u63d0\u4ea4");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton1ActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jButton2.setText("\u8fd4\u56de");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(22, 22, 22)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						jLabel2)
																				.addComponent(
																						jLabel1))
																.addGap(29, 29,
																		29)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						Password_Confirm,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						166,
																						Short.MAX_VALUE)
																				.addComponent(
																						Password_New,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						166,
																						Short.MAX_VALUE)))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(18, 18,
																		18)
																.addComponent(
																		jButton1)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		93,
																		Short.MAX_VALUE)
																.addComponent(
																		jButton2)
																.addGap(18, 18,
																		18)))
								.addGap(38, 38, 38)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGap(42, 42, 42)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel1)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		48,
																		Short.MAX_VALUE)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel2)
																				.addComponent(
																						Password_Confirm,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(35, 35,
																		35))
												.addComponent(
														Password_New,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton1)
												.addComponent(jButton2))
								.addGap(31, 31, 31)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
			throws Exception {
		Connection con = dbUtil.getCon();
		String newPW = new String(this.Password_New.getPassword());
		String confirmPW = new String(this.Password_Confirm.getPassword());
		if (!newPW.equals(confirmPW)) {
			JOptionPane.showMessageDialog(null, "两次输入的密码不同");
			return;
		}

		if (dbLogUserDao.setPassword(con, ID, newPW)) {
			JOptionPane.showMessageDialog(null, "密码修改成功，请牢记新密码");
			this.dispose();
			new LogFrm().setVisible(true);
		} else {
			JOptionPane.showMessageDialog(null, "密码修改失败");
		}
		con.close();
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
		new FindBackPWFrm_sub().setVisible(true);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new FindBackPWFrm().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JPasswordField Password_Confirm;
	private javax.swing.JPasswordField Password_New;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	// End of variables declaration//GEN-END:variables

}