/*
 * SearchingSimplePanel.java
 *
 * Created on __DATE__, __TIME__
 */

package com.Zs.View;

import java.awt.Label;
import java.sql.Connection;
import java.sql.SQLException;

import javax.swing.DefaultListModel;
import javax.swing.JList;

import ZsUtil.ZsUtil;

import com.Zs.DbDao.DbRecord_4ItemDao;
import com.Zs.DbUtil.DbUtil;

/**
 *
 * @author  __USER__
 */
public class SearchingSimplePanel extends javax.swing.JPanel {

	private DefaultListModel defaultListModel = new DefaultListModel();
	private DefaultListModel m = new DefaultListModel();
	DbUtil dbUtil = new DbUtil();
	DbRecord_4ItemDao dbRecord_4ItemDao = new DbRecord_4ItemDao();

	/** Creates new form SearchingSimplePanel */
	public SearchingSimplePanel() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		SearchingSimpleList = new javax.swing.JList();
		jButton1 = new javax.swing.JButton();
		KM_CheckBox = new javax.swing.JCheckBox();
		ML_CheckBox = new javax.swing.JCheckBox();
		FFRQ_CheckBox = new javax.swing.JCheckBox();
		All_CheckBox = new javax.swing.JCheckBox();
		jLabel2 = new javax.swing.JLabel();

		jLabel1.setText("\u7b80\u5355\u68c0\u7d22\u6846");

		SearchingSimpleList.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "请选择您要查询的内容" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane1.setViewportView(SearchingSimpleList);

		jButton1.setText("\u67e5\u8be2\u8bb0\u5f55");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton1ActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		KM_CheckBox.setText("\u5f00\u95e8");
		KM_CheckBox.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				KM_CheckBoxActionPerformed(evt);
			}
		});

		ML_CheckBox.setText("\u95e8\u94c3");

		FFRQ_CheckBox.setText("\u975e\u6cd5\u5165\u4fb5");

		All_CheckBox.setSelected(true);
		All_CheckBox.setText("\u6240\u6709\u8bb0\u5f55");

		jLabel2.setText("jLabel2");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(55, 55,
																		55)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										KM_CheckBox)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addComponent(
																										ML_CheckBox)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addComponent(
																										FFRQ_CheckBox)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										All_CheckBox))
																				.addComponent(
																						jLabel1)))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jButton1))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jScrollPane1,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		357,
																		Short.MAX_VALUE)))
								.addContainerGap())
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(275, Short.MAX_VALUE)
								.addComponent(jLabel2).addGap(65, 65, 65)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(KM_CheckBox)
												.addComponent(ML_CheckBox)
												.addComponent(FFRQ_CheckBox)
												.addComponent(All_CheckBox))
								.addGap(2, 2, 2)
								.addComponent(jLabel2)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										282, Short.MAX_VALUE)
								.addGap(18, 18, 18).addComponent(jButton1)
								.addContainerGap()));
	}// </editor-fold>
	//GEN-END:initComponents

	private void KM_CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
			throws Exception {
		Connection con = dbUtil.getCon();
		defaultListModel.clear();
		m.clear();
		defaultListModel = this.getList(con);//得到没有时间约束的数据
		for (int i = 0; i < defaultListModel.getSize(); i++) {
			int length = defaultListModel.get(i).toString().length();//将10150311095447转化为2015年03月11日09时54分47秒
			String str = DbRecord_4ItemDao
					.getStringFromSqlDate(defaultListModel.get(i).toString()
							.substring(length - 14));
			m.addElement(defaultListModel.get(i).toString()
					.substring(0, length - 14)
					+ str);
		}

		//System.out.println(str6);
		
		jLabel2.setText(m.size()+"");
		this.showList(m);
		dbUtil.closeCon(con);
	}


	private DefaultListModel getList(Connection con) throws SQLException {
		DefaultListModel m = new DefaultListModel();
		m.clear();
		if (All_CheckBox.isSelected()) {
			m = dbRecord_4ItemDao.getAll(con);
		} else {
			if (KM_CheckBox.isSelected()) {
				m = ZsUtil.DftMd_Add(m,
						dbRecord_4ItemDao.getSearchingDb(con, "DoSth", "开门在"));
			}
			if (ML_CheckBox.isSelected()) {
				m = ZsUtil.DftMd_Add(m,
						dbRecord_4ItemDao.getSearchingDb(con, "DoSth", "按门铃在"));
			}
			if (FFRQ_CheckBox.isSelected()) {
				m = ZsUtil
						.DftMd_Add(m, dbRecord_4ItemDao.getSearchingDb(con,
								"DoSth", "非法入侵在"));
			}
		}

		return m;
	}

	private void showList(DefaultListModel SearchingExpertModel) {

		this.SearchingSimpleList.setModel(SearchingExpertModel);
		this.SearchingSimpleList = new JList(SearchingExpertModel);
		this.SearchingSimpleList.invalidate();
		this.SearchingSimpleList.repaint();
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JCheckBox All_CheckBox;
	private javax.swing.JCheckBox FFRQ_CheckBox;
	private javax.swing.JCheckBox KM_CheckBox;
	private javax.swing.JCheckBox ML_CheckBox;
	private javax.swing.JList SearchingSimpleList;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables
	
	//*****************返回查询的数据
	public DefaultListModel getAllList() throws Exception
	{
		String TimeStr = null;
		Connection con = dbUtil.getCon();
		defaultListModel.clear();
		m.clear();
		defaultListModel = this.getList(con);//得到没有时间约束的数据
		for (int i = 0; i < defaultListModel.getSize(); i++) {
			int length = defaultListModel.get(i).toString().length();//将10150311095447转化为2015年03月11日09时54分47秒
			TimeStr = "&"+defaultListModel.get(i).toString()
			.substring(length - 14);
			String str = DbRecord_4ItemDao
					.getStringFromSqlDate(defaultListModel.get(i).toString()
							.substring(length - 14));
			m.addElement(defaultListModel.get(i).toString()
					.substring(0, length - 14)
					+ str+TimeStr);
			System.out.println(m.get(i));
			System.out.println(i+"");
		}

		//System.out.println(str6);
		this.showList(m);
		dbUtil.closeCon(con);
		return m;
	}

}