/*
 * SignFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.Zs.View;

import java.sql.Connection;

import javax.swing.JOptionPane;

import ZsUtil.ZsUtil;

import com.Zs.DbDao.DbLogUserDao;
import com.Zs.DbDao.DbLogUserMemb;
import com.Zs.DbUtil.DbUtil;

/**
 *
 * @author  __USER__
 */
public class SignFrm extends javax.swing.JFrame {
	DbUtil dbUtil = new DbUtil();
	DbLogUserDao dbLogUserDao = new DbLogUserDao();
	public MainFrm main =null;
	
	public MainFrm getMain() {
		return main;
	}

	public void setMain(MainFrm main) {
		this.main = main;
	}

	/** Creates new form SignFrm */
	public SignFrm() {
		initComponents();
		//设置fram居中显示
		this.setLocationRelativeTo(null);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		userTxt = new javax.swing.JTextField();
		passwordTxt = new javax.swing.JPasswordField();
		telTxt = new javax.swing.JTextField();
		q1Txt = new javax.swing.JTextField();
		a1Txt = new javax.swing.JTextField();
		q2Txt = new javax.swing.JTextField();
		a2Txt = new javax.swing.JTextField();
		q3Txt = new javax.swing.JTextField();
		a3Txt = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setUndecorated(true);

		jLabel1.setText("\u7528\u6237\u540d");

		jLabel2.setText("\u5bc6   \u7801");

		jLabel3.setText("T e l");

		jLabel4.setText("\u95ee\u9898\u4e00\uff1a");

		jLabel5.setText("\u95ee\u9898\u4e00\u7b54\u6848\uff1a");

		jLabel6.setText("\u95ee\u9898\u4e8c\uff1a");

		jLabel7.setText("\u95ee\u9898\u4e8c\u7b54\u6848\uff1a");

		jLabel8.setText("\u95ee\u9898\u4e09\uff1a");

		jLabel9.setText("\u95ee\u9898\u4e09\u7b54\u6848\uff1a");



		telTxt.setText("jTextField2");

		q1Txt.setText("jTextField3");

		a1Txt.setText("jTextField4");

		q2Txt.setText("jTextField5");

		a2Txt.setText("jTextField6");

		q3Txt.setText("jTextField7");

		a3Txt.setText("jTextField8");

		jButton1.setText("\u786e\u5b9a");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u8fd4\u56de");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(40, 40, 40)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel1)
												.addComponent(jLabel2)
												.addComponent(jLabel3)
												.addComponent(jLabel4)
												.addComponent(jLabel5)
												.addComponent(jLabel6)
												.addComponent(jLabel7)
												.addComponent(jLabel8)
												.addComponent(jLabel9)
												.addComponent(jButton1))
								.addGap(30, 30, 30)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
																.addComponent(
																		userTxt)
																.addComponent(
																		passwordTxt,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		187,
																		Short.MAX_VALUE)
																.addComponent(
																		telTxt)
																.addComponent(
																		q1Txt)
																.addComponent(
																		a1Txt)
																.addComponent(
																		q2Txt)
																.addComponent(
																		a2Txt)
																.addComponent(
																		q3Txt)
																.addComponent(
																		a3Txt))
												.addComponent(jButton2))
								.addContainerGap(71, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(43, 43, 43)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(
														userTxt,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														passwordTxt,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(
														telTxt,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel4)
												.addComponent(
														q1Txt,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel5)
												.addComponent(
														a1Txt,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel6)
												.addComponent(
														q2Txt,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel7)
												.addComponent(
														a2Txt,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel8)
												.addComponent(
														q3Txt,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel9)
												.addComponent(
														a3Txt,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										27, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton2)
												.addComponent(jButton1))
								.addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		String password = new String(passwordTxt.getPassword());
		Connection con = null;
		//如果 有空的
		if (ZsUtil.stringIsEmpty(userTxt.getText())
				|| ZsUtil.stringIsEmpty(password)
				|| ZsUtil.stringIsEmpty(telTxt.getText())
				|| ZsUtil.stringIsEmpty(q1Txt.getText())
				|| ZsUtil.stringIsEmpty(a1Txt.getText())
				|| ZsUtil.stringIsEmpty(q2Txt.getText())
				|| ZsUtil.stringIsEmpty(a2Txt.getText())
				|| ZsUtil.stringIsEmpty(q3Txt.getText())
				|| ZsUtil.stringIsEmpty(a3Txt.getText())) {
			JOptionPane.showMessageDialog(null, "信息未填完整！");
			return;
		}

		DbLogUserMemb dbLogUser = new DbLogUserMemb(userTxt.getText(),
				new String(passwordTxt.getPassword()), telTxt.getText(),
				q1Txt.getText(), a1Txt.getText(), q2Txt.getText(),
				a2Txt.getText(), q3Txt.getText(), a3Txt.getText());
		try {
			con = dbUtil.getCon();
			int result = dbLogUserDao.logUserAdd(con, dbLogUser);
			if (result == 1) {
				JOptionPane.showMessageDialog(null, "用户注册成功！");
			} else {
				JOptionPane.showMessageDialog(null, "用户注册失败！");
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, "用户注册失败！");
		}

	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
		main.setEnabled(true);
		main.setVisible(true);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new SignFrm().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextField a1Txt;
	private javax.swing.JTextField a2Txt;
	private javax.swing.JTextField a3Txt;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPasswordField passwordTxt;
	private javax.swing.JTextField q1Txt;
	private javax.swing.JTextField q2Txt;
	private javax.swing.JTextField q3Txt;
	private javax.swing.JTextField telTxt;
	private javax.swing.JTextField userTxt;
	// End of variables declaration//GEN-END:variables

}